add evaluation

diff --git a/trunk/lib/DETECTIONS b/trunk/lib/DETECTIONS
--- a/trunk/lib/DETECTIONS
+++ b/trunk/lib/DETECTIONS
@@ -1,4 +1,28 @@
 #/usr/bin/bash
+
+evaluation_ini(){
+
+	  ### get number of file to create
+
+	  let "NB_FILE_TO_CREATE = $NB_FILE_TO_CREATE + 1" 
+ 
+
+	  ### get average time for this format
+
+	  TIME_EVALUATION=$(cat ${APP_DIR}/log/timer.log  |grep "${INPUT_SIZE_CATEGORY}TO$PREFIX-$FF_FORMAT-$PLAY_SIZE" |awk -F "\t" '{ n++; SUM += $2 } END { print SUM/n }')
+	  TIME_EVALUATION=$(echo "$TIME_EVALUATION * $DURATION_S * $CPUS_AVERAGE/1000" |bc )
+	  let "TOTAL_TIME_EVALUATION =$TOTAL_TIME_EVALUATION + $TIME_EVALUATION"
+
+}
+
+evaluation_check(){
+
+	  ### check if the output file is created
+	  get_file_infos "${DIRECTORY}/$SUBDIR/${OUTPUT}${PLAY_SIZE}.${FF_FORMAT}"
+	  let "NB_FILE_CREATED = $NB_FILE_CREATED + $FILE_INFOS_STATUS"
+
+}
+
 get_file_infos(){
 
 		if [[ -f $1 &&  $SYSTEM == "Linux" ]]
@@ -16,7 +40,7 @@ get_file_infos(){
 
 		FILE_INFOS="$FILE_INFOS<file>\\n"
 		FILE_INFOS="$FILE_INFOS<path>$1</path>\\n"
-		FILE_INFOS="$FILE_INFOS<format>$(file   $1 |awk -F , '{print $2}'|tr -d " ")</format>\\n"
+		FILE_INFOS="$FILE_INFOS<format>$FF_FORMAT</format>\\n"
 		
 
 		 [[ $SYSTEM == "Linux" ]] && FILE_INFOS="$FILE_INFOS<md5>$(md5sum -b $1|grep -o ".* "|tr -d " ")</md5>\\n"
@@ -24,52 +48,59 @@ get_file_infos(){
 		
 		FILE_INFOS="$FILE_INFOS<size>$RESULTS_SIZE</size>\\n"
 		FILE_INFOS="$FILE_INFOS</file>\\n"
-		return 1
-		else
-		FILE_INFOS="error: file not created ($1)"
+		FILE_INFOS_STATUS=1
 		return 0
+		else
+		FILE_INFOS_STATUS=0
+		FILE_INFOS="error: file not created ($1)"
+		return 1
 		fi 
 
 }
 
 
-get_general_infos () {	      
-	      GENERAL_INFOS=""
-	      FORMAT=""
-	      FILE_SIZE=0
-	      DURATION=0
-	      BITERATE=0
-	      VIDEO_COUNT=0
-	      VIDEO_COUNT=0
+get_general_infos () {	     
+ 
+GENERAL_INFOS=""
+FORMAT=""
+FILE_SIZE=0
+DURATION=0
+BITERATE=0
+VIDEO_COUNT=0
+VIDEO_COUNT=0
 	      
 
-	     # get some general info about the video
+	      ### get some general info about the video
+
 	      GENERAL_INFOS=`mediainfo "--Inform=General;FORMAT='%Format%' FILE_SIZE=%FileSize% DURATION=%Duration% BITERATE=%OverallBitRate% VIDEO_COUNT=%VideoCount% AUDIO_COUNT=%AudioCount%" ${INPUT}`
-	      #echo "$GENERAL_INFOS"
+
 	      eval "$GENERAL_INFOS"
 
-		[[ $DEBUG -gt 0 ]] 	 &&  echo -e "\\n${cyan}$(box "General informations")${NC}" 
-		save_info "\n# General informations\n"
-	      # display the file name and the size
-	      
-		[[ $DEBUG -gt 0 ]] && echo -e "FILE_PATH=${GREEN}\"$INPUT\"${NC}" || echo -e "${BLUE}$INPUT${NC}"
-		save_info "FILE_PATH=\"$INPUT\""
-		 
-		if [[ $FILE_SIZE -gt 1 ]]
-		then
-		[[ $DEBUG -gt 0 ]] && echo -e "FILE_SIZE=${GREEN}$FILE_SIZE${NC}\\t# `echo "$FILE_SIZE / 1024 /1024 "| bc `MB"
+	      [[ $DEBUG -gt 0 ]] 	 &&  echo -e "\\n${cyan}$(box "General informations")${NC}" 
+	      save_info "\n# General informations\n"
 
-		else
-   
-		echo -e "FILE_SIZE=${RED}$FILE_SIZE${NC}\\t#`echo "$FILE_SIZE / 1024 /1024 "| bc `MB"
+	      ### display the file name and the size
 
-		fi
-		save_info "FILE_SIZE=$FILE_SIZE"
+	      [[ $DEBUG -gt 0 ]] && echo -e "FILE_PATH=${GREEN}\"$INPUT\"${NC}" || echo -e "${BLUE}$INPUT${NC}"
+	      save_info "FILE_PATH=\"$INPUT\""
+
+	      if [[ $FILE_SIZE -gt 1 ]]
+	      then
+
+	      [[ $DEBUG -gt 0 ]] && echo -e "FILE_SIZE=${GREEN}$FILE_SIZE${NC}\\t# `echo "$FILE_SIZE / 1024 /1024 "| bc `MB"
+
+	      else
+
+	      echo -e "FILE_SIZE=${RED}$FILE_SIZE${NC}\\t#`echo "$FILE_SIZE / 1024 /1024 "| bc `MB"
+
+	      fi
+
+	      save_info "FILE_SIZE=$FILE_SIZE"
 
 
 
 
-	      # check the container FORMAT
+	      ### check the container FORMAT
 
 	      if [[ ! -z ` grep  "^${FORMAT}$" ${APP_DIR}/config/FORMATS ` ]]
 	      then
@@ -77,68 +108,87 @@ get_general_infos () {
 	      else
 	      [[ $DEBUG -gt 0 ]] && echo -e "FORMAT=${YELLOW}$FORMAT${NC}"
 	      fi
+
 	      save_info "FORMAT=\"$FORMAT\""
 
 
 
 
-	      # check the duration of the video	 
-		 
-		 # duration null try with mplayer 
+	      ### check the duration of the video
+
+	 
+
+	      ### duration null try with mplayer 
+
 	      if [[ -z $DURATION ||  $DURATION == 0 ]]
-		 then
-		 get_duration_mplayer
-		 
-		 # set DURATION to  DURATION_MPLAYER value  in miliseconds
-		 DURATION=`echo "$DURATION_MPLAYER * 1000"|bc `
-		 # set DURATION_S to  DURATION_MPLAYER value  in seconds
-		 DURATION_S=${DURATION_MPLAYER%.??}
-		 else		 
+	      then
+
+	      get_duration_mplayer
+
+	      ### set DURATION to DURATION_MPLAYER value  in miliseconds
+
+	      DURATION=`echo "$DURATION_MPLAYER * 1000"|bc `
+
+	      ### set DURATION_S to  DURATION_MPLAYER value  in seconds
+
+	      DURATION_S=${DURATION_MPLAYER%.??}
+
+	      else		 
+
 	      DURATION_S=`echo "$DURATION / 1000"|bc`
-		 fi
+
+	      fi
 		 
 		 
 	      if [[  $DURATION_S -lt  $MINIMUM_DURATION ]] 
 	      then
+
 	      ERROR="ERROR: Duration of the video is ($DURATION_S secondes).The minimun duration for a video is ($MINIMUM_DURATION secondes)  "
 	      echo -e ${RED}${ERROR}${NC}
 	      echo $ERROR >> ${DIRECTORY}/${OUTPUT}/error.txt   
+
 	      else
+
 	      [[ $DEBUG -gt 0 ]] && echo -e "DURATION=${GREEN}$DURATION_S${NC}"
 	      CROPSTART=`echo ${DURATION_S} / 2|bc`
-	      fi
-	      save_info "DURATION=$DURATION"
 
+	      fi
+
+	      save_info "DURATION=$DURATION"
+	      save_info "DURATION_S=$DURATION_S"
 
 	      
-	      # Get the general bitrate by calculation
+	      ### Get the general bitrate by calculation
 	      
 	      BITERATE_CALC=$(echo "scale=10;$FILE_SIZE * 8 / ($DURATION/1000)"|bc)
 	      BITERATE_CALC=${BITERATE_CALC%.*}
 		 
 		 
-	      # Check the general bitrate of thevideo
+	      ### Check the general bitrate of thevideo
 	      
 	      if [[ ! -z $BITERATE && ! -z $BITERATE_CALC && $BITERATE == $BITERATE_CALC  ]]
 	      then
+
 	      FF_BITERATE=$(echo "$BITERATE / 1000 "|bc)
 	      FF_BITERATE=${FF_BITERATE%.*}k
 		 
-				# check the size
+				### check the size
 				if [[ $BITERATE -gt $MINIMUM_BITERATE ]]
 				then
 				[[ $DEBUG -gt 0 ]] && echo -e "BITERATE=${GREEN}$BITERATE${NC}\\t# $FF_BITERATE"
 				else
 				WARNING="WARNING: General biterate  of the video is ( $BITERATE / $FF_BITERATE ).The minimun biterate for a $FORMAT video is ($MINIMUM_BITERATE)  "
 				echo -e ${PINK}${WARNING}${NC}
-				echo $WARNING >> ${DIRECTORY}/${OUTPUT}/error.txt
+				echo $WARNING >> ${DIRECTORY}/${OUTPUT}/warning.txt
 				fi
 		 
-		 # BITERATE not detected from mediainfo take the BITERATE_CALC instead
-		 elif [[  -z $BITERATE && ! -z $BITERATE_CALC ]]
+	      ### BITERATE not detected from mediainfo take the BITERATE_CALC instead
+
+	      elif [[  -z $BITERATE && ! -z $BITERATE_CALC ]]
 	      then
-		 BITERATE=$BITERATE_CALC
-		 FF_BITERATE=$(echo "$BITERATE / 1000 "|bc)
+
+	      BITERATE=$BITERATE_CALC
+	      FF_BITERATE=$(echo "$BITERATE / 1000 "|bc)
 	      FF_BITERATE=${FF_BITERATE%.*}k
 
 				# check the size
@@ -148,121 +198,164 @@ get_general_infos () {
 				else
 				WARNING="WARNING: General biterate  of the video is ( $BITERATE / $FF_BITERATE ).The minimun biterate for a $FORMAT video is ($MINIMUM_BITERATE)  "
 				echo -e ${PINK}${WARNING}${NC}
-				echo $WARNING >> ${DIRECTORY}/${OUTPUT}/error.txt
+				echo $WARNING >> ${DIRECTORY}/${OUTPUT}/warning.txt
 				fi
 
 	      fi
+
 	      save_info "BITERATE=$BITERATE"
 
 
 
-	      # Chek the number of video stream
+	      ### Chek the number of video stream
+
+
+	      ### 1 video detected
 	      
 	      if [[ $VIDEO_COUNT == 1 ]] 
 	      then
+
 	      [[ $DEBUG -gt 0 ]] && echo -e "VIDEO_COUNT=${GREEN}$VIDEO_COUNT${NC}"
 	      save_info "VIDEO_COUNT=$VIDEO_COUNT"
+
+	      ### more than 1 video
+	      
+	      elif [[ $VIDEO_COUNT -gt 1 ]]
+	      then
+
+	      WARNING="# WARNING: More than 1 video stream is detected ($VIDEO_COUNT)"
+	      echo -e ${PINK}${WARNING}${NC}
+	      echo $WARNING >> ${DIRECTORY}/${OUTPUT}/warning.txt 
+	      save_info "VIDEO_COUNT=$VIDEO_COUNT"
+
+	      ### video missing or not detected
+
 	      else
-	      ERROR="# ERROR: 1 video stream is needed (Detection: $VIDEO_COUNT)."
+
+	      ERROR="#ERROR: 1 video stream is needed (Detection: $VIDEO_COUNT)."
 	      echo -e ${RED}${ERROR}${NC}
 	      echo $ERROR >> ${DIRECTORY}/${OUTPUT}/error.txt 
-	      save_info "$ERROR"
+	      #save_info "$ERROR"
+
 	      fi
 	      
-	      # Chek the number of audio stream	      
+	      ### Chek the number of audio stream	      
+
+	      ### 1 audio
 	      
 	      if [[ $AUDIO_COUNT == 1 ]] 
 	      then
 	      [[ $DEBUG -gt 0 ]] && echo -e "AUDIO_COUNT=${GREEN}$AUDIO_COUNT${NC}"
 	      save_info "AUDIO_COUNT=$AUDIO_COUNT"
+
+	      ### more than 1 audio
 	      
-		 elif [[ $AUDIO_COUNT -gt 1 ]]
-		 then
-		 WARNING="# WARNING: More than 1 audio stream is detected ($AUDIO_COUNT)"
+	      elif [[ $AUDIO_COUNT -gt 1 ]]
+	      then
+
+	      WARNING="# WARNING: More than 1 audio stream is detected ($AUDIO_COUNT)"
 	      echo -e ${PINK}${WARNING}${NC}
-	      echo $WARNING >> ${DIRECTORY}/${OUTPUT}/error.txt 
-	      save_info "$WARNING"
+	      echo $WARNING >> ${DIRECTORY}/${OUTPUT}/warning.txt 
+	      save_info "AUDIO_COUNT=$AUDIO_COUNT"
+
+	      ### audio missing or not detected
+
 	      else
+
 	      ERROR="# ERROR: 1 audio stream is needed (Detection: $AUDIO_COUNT)"
 	      echo -e ${RED}${ERROR}${NC}
 	      echo $ERROR >> ${DIRECTORY}/${OUTPUT}/error.txt 
-	      save_info "$ERROR"
+
 	      fi
+
+
 }
 
 check_comp(){
-		 
-		 
-		 [[ $DEBUG -gt 0 ]] &&  echo -e "\\n${BLUE}$(box "Compatibility")${NC}"
-		 save_info "\n# Compatibility\n"
-		 
-		 
-		 ### check if the video codec is supPorted by ffmpeg ###
-		 
-		 
-		 FFMPEG_TEST=`${FFMPEG} -i "$INPUT" -sameq -vframes 1 -y "${DIRECTORY}/${SUBDIR}/test.jpg" 2>&1 `   
-		
-		 FFMPEG_TAIL="`echo "$FFMPEG_TEST"|tail  -n 1   `"	
-		 FFMPEG_HEAD="`echo "$FFMPEG_TEST"| head -25 `"
-		 FFMPEG_VIDEO=`echo "$FFMPEG_TAIL"|grep -o "^video:[1-9][0-9]*kB" `
-		 
-		 if [[ ! -z $FFMPEG_VIDEO ]]
-		 then
-		 FFMPEG_VIDEO=1
-		 [[ $DEBUG > 0 ]] && echo -e "FFMPEG_VIDEO=${GREEN}$FFMPEG_VIDEO${NC} "
-		 save_info "FFMPEG_VIDEO=1"
-		 else
-		 FFMPEG_VIDEO=$FFMPEG_VIDEO
-		  
-		  ERROR="FFMPEG_VIDEO=$FFMPEG_VIDEO"
 
-		  [[ $DEBUG > 1 ]] && echo "$FFMPEG_HEAD"
-				  
 
-		  echo -e "${RED}${ERROR}${NC}"
-		  save_info "$ERROR"
-		  
-		  # Video codec supported by ffmpeg
-		  [[ $DEBUG > 0 ]] && echo  ${FFMPEG_TAIL}  
-		  echo -e ${ERROR} ${FFMPEG_HEAD}  >> ${DIRECTORY}/${OUTPUT}/error.txt    
+		[[ $DEBUG -gt 0 ]] &&  echo -e "\\n${BLUE}$(box "Compatibility")${NC}"
+
+		save_info "\n# Compatibility\n"
+
+
+		### check if the video codec is supPorted by ffmpeg ###
+
+
+		FFMPEG_TEST=`${FFMPEG} -i "$INPUT" -sameq -vframes 1 -y "${DIRECTORY}/${SUBDIR}/test.jpg" 2>&1 `   
+
+		FFMPEG_TAIL="`echo "$FFMPEG_TEST"|tail  -n 1   `"	
+		FFMPEG_HEAD="`echo "$FFMPEG_TEST"| head -25 `"
+		FFMPEG_VIDEO=`echo "$FFMPEG_TAIL"|grep -o "^video:[1-9][0-9]*kB" `
+
+		if [[ ! -z $FFMPEG_VIDEO ]]
+		then
+
+		FFMPEG_VIDEO=1
+		[[ $DEBUG > 0 ]] && echo -e "FFMPEG_VIDEO=${GREEN}$FFMPEG_VIDEO${NC} "
+		save_info "FFMPEG_VIDEO=1"
+
+		else
+
+		FFMPEG_VIDEO=$FFMPEG_VIDEO
+
+		ERROR="FFMPEG_VIDEO=$FFMPEG_VIDEO"
+
+		[[ $DEBUG > 1 ]] && echo "$FFMPEG_HEAD"
 			  
-		  fi
-				
-				
 
-				
-		
-				
-		 
-		 ### check if the AUDIO  codec is supported by ffmpeg ###
-		 
+		echo -e "${RED}${ERROR}${NC}"
+		save_info "$ERROR"
+
+		### Video codec supported by ffmpeg
+
+		[[ $DEBUG > 0 ]] && echo  ${FFMPEG_TAIL}  
+		echo -e ${ERROR} ${FFMPEG_HEAD}  >> ${DIRECTORY}/${OUTPUT}/error.txt    
+		  
+		fi
+			
+			
+
+			
+
+			
+
+		### check if the AUDIO  codec is supported by ffmpeg ###
+
+
+
+
 		FFMPEG_TEST=`${FFMPEG} -i "$INPUT" -t 1 -ac 2 -y "${DIRECTORY}/${SUBDIR}/test.mp3" 2>&1 `   
 		#echo "$FFMPEG_TEST"
-		
-		 FFMPEG_TAIL="`echo "$FFMPEG_TEST"|tail  -n 1   `"	
-		 #echo $FFMPEG_TAIL
-		 FFMPEG_HEAD="`echo "$FFMPEG_TEST"| head -25 `"
-		 FFMPEG_AUDIO=`echo "$FFMPEG_TAIL"|grep -o " audio:[1-9][0-9]*kB" `
-		 
-		  if [[ ! -z FFMPEG_AUDIO ]]
-		  then
-		  FFMPEG_AUDIO=1
-		  [[ $DEBUG > 0 ]] && echo -e "FFMPEG_AUDIO=${GREEN}$FFMPEG_AUDIO${NC} "
-		  save_info "FFMPEG_AUDIO=$FFMPEG_AUDIO"
-		  else
-		  FFMPEG_AUDIO=1
-		  ERROR="FFMPEG_AUDIO=$FFMPEG_AUDIO"
 
-		  [[ $DEBUG > 1 ]] && echo "$FFMPEG_HEAD"
-		  save_info "$ERROR"
-		  
-		  echo -e "${RED}${ERROR}${NC}"
-		  [[ $DEBUG > 0 ]] && echo  ${FFMPEG_TAIL}
-		  
-		  
-		  echo -e ${ERROR} ${FFMPEG_HEAD}  >> ${DIRECTORY}/${OUTPUT}/error.txt    
-		  
-		  fi
+		FFMPEG_TAIL="`echo "$FFMPEG_TEST"|tail  -n 1   `"	
+		#echo $FFMPEG_TAIL
+		FFMPEG_HEAD="`echo "$FFMPEG_TEST"| head -25 `"
+		FFMPEG_AUDIO=`echo "$FFMPEG_TAIL"|grep -o " audio:[1-9][0-9]*kB" `
+
+		if [[ ! -z FFMPEG_AUDIO ]]
+		then 
+
+		FFMPEG_AUDIO=1
+		[[ $DEBUG > 0 ]] && echo -e "FFMPEG_AUDIO=${GREEN}$FFMPEG_AUDIO${NC} "
+		save_info "FFMPEG_AUDIO=$FFMPEG_AUDIO"
+
+		else
+
+		FFMPEG_AUDIO=1
+		ERROR="FFMPEG_AUDIO=$FFMPEG_AUDIO"
+
+		[[ $DEBUG > 1 ]] && echo "$FFMPEG_HEAD"
+
+		save_info "$ERROR"
+
+		echo -e "${RED}${ERROR}${NC}"
+		[[ $DEBUG > 0 ]] && echo  ${FFMPEG_TAIL}
+
+
+		echo -e ${ERROR} ${FFMPEG_HEAD}  >> ${DIRECTORY}/${OUTPUT}/error.txt    
+
+		fi
 		  
 		  
 		ID_VIDEO_ID=0
@@ -306,17 +399,28 @@ check_comp(){
 		
 		if [[ ! -z $ID_VIDEO_CODEC ]]
 		then
+
 		MPLAYER_VIDEO=1
 		[[ $DEBUG > 0 ]] && echo -e "MPLAYER_VIDEO=${GREEN}$MPLAYER_VIDEO${NC}\\t\\t# $ID_VIDEO_CODEC"
 		save_info "MPLAYER_VIDEO=$MPLAYER_VIDEO"
+
 		else
+
 		MPLAYER_VIDEO=0		
 		ERROR="MPLAYER_VIDEO=$MPLAYER_VIDEO"
 		save_info "$ERROR"
 		echo -e "${RED}${ERROR}${NC}\\n"
 		echo -e ${ERROR}  >> ${DIRECTORY}/${OUTPUT}/error.txt 
+
 		fi
+
+
+
+
 		### check if audio can be read with mplayer  ###
+
+
+
 		
 		if [[ ! -z $ID_AUDIO_CODEC ]]
 		then
@@ -562,11 +666,13 @@ VCODEC=""
 	      FF_VBITERATE=${FF_VBITERATE%.*}k
 	      [[ $DEBUG -gt 0 ]] && echo -e "VBITERATE=${GREEN}$VBITERATE${NC}\\t# $FF_VBITERATE"
 	
-		 # VBITERATE too small
+	      ### VBITERATE too small
+
 	      else
+
 	      WARNING="WARNING: Video biterate is ($VBITERATE $VFF_BITERATE ).The minimun biterate for a $VFORMAT video is ($MINIMUM_VBITERATE)  "
 	      echo -e ${PINK}${WARNING}${NC}
-	      echo $WARNING >> ${DIRECTORY}/${OUTPUT}/error.txt
+	      echo $WARNING >> ${DIRECTORY}/${OUTPUT}/warning.txt
 	      fi
 	      save_info  "VBITERATE=$VBITERATE"
 	      
@@ -722,15 +828,21 @@ get_audio_infos() {
 		  # ABITERATE is a standar
 		  if [[ ! -z ` grep  "^${FF_ABITERATE}$" ${APP_DIR}/config/ABITRATES ` ]]
 		  then
+
 		  [[ $DEBUG -gt 0 ]] && echo -e "ABITERATE=${GREEN}$FF_ABITERATE${NC}\\t# $ABITERATE\\t$ABITERATE_NOTICE"
-		  # too small
+
+		  ### too small
+
 		  elif [[ $FF_ABITERATE -gt $MINIMUM_ABITERATE ]]
 		  then
+
 		  echo -e "ABITERATE=${YELLOW}$FF_ABITERATE${NC}\\t$ABITERATE\\t# $ABITERATE_NOTICE"
+
 		  else
+
 		  WARNING="WARNING: audio biterate is ($FF_ABITERATE $ABITERATE ).The minimun biterate for a $AFORMAT audio is ($MINIMUM_ABITERATE)  "
 		  echo -e ${PINK}${WARNING}${NC}
-		  echo $WARNING >> ${DIRECTORY}/${OUTPUT}/error.txt
+		  echo $WARNING >> ${DIRECTORY}/${OUTPUT}/warning.txt
 		  fi
 		  save_info "ABITERATE=$ABITERATE"
 
@@ -912,44 +1024,67 @@ cropdetection() {
 
 
 function get_extra_infos () {
-# just testing
-	      # check the BPF of the video (test)
-	      
-	      echo -e "\\n${cyan}$(box "Extra informations")${NC}\\n"
-	      
-	      NB_FRAMES=$(mediainfo "--Inform=Video;%FrameCount%" ${INPUT})
-	      STREAMSIZE=$(mediainfo "--Inform=Video;%StreamSize%" ${INPUT})
-	      NB_PIXELS=$(echo "$WIDTH * $HEIGHT"|bc)
-	      if [[ ! -z $STREAMSIZE && ! -z $NB_FRAMES ]]
-	      then
-	      NB_PIXELS=$(echo "$WIDTH * $HEIGHT"|bc)
-	      BPF=$(echo "($STREAMSIZE * 1080 / $NB_FRAMES) / $NB_PIXELS  "|bc)
-	      echo -e "fredo BPF1=${GREEN}${BPF}${NC}"
-	      fi
-	      
-	      # check the BPF of the video
-	      
-	      BPF=$(mediainfo "--Inform=Video;%Bits-(Pixel*Frame)%" ${INPUT})
-	           
-	      if [[ $BPF < $MINIMUM_BPF && ! -z $BPF ]] 
-	      then
-	      WARNING="WARNING: BPF quality  of the video is ($BPF).The minimun quality is ($MINIMUM_BPF)  "
-	      echo -e "${PINK}$WARNING${NC}"
-	      echo $WARNING >> ${DIRECTORY}/${OUTPUT}/error.txt
-	      else
-	      echo  -e "BPF=${GREEN}${BPF}${NC}"
-	      fi
-	      
 
 	      
-	      VBRPP=$(echo "scale=1;$BITERATE / $NB_PIXELS  "|bc)
-	      if [[ $VBRPP <  1.5  ]]
-	      then
-	      WARNING="WARNING: VBRPP quality  of the video is ($VBRPP).The minimun quality is (1)  "
-	      echo -e "${PINK}$WARNING${NC}"
-	      echo $WARNING >> ${DIRECTORY}/${OUTPUT}/error.txt
-	      else
-	      echo -e "fredo VBRPP=${GREEN}${VBRPP}${NC}"
-	      fi
+	      [[ $DEBUG -gt 0 ]] && echo -e "\\n${cyan}$(box "extra infos")${NC}\\n"
+	      save_info "\n# extra infos\n"
+
+	      ### get the INPUT_SIZE_CATEGORY 1 to 8
+
+	      [[ $NEW_WIDTH -lt 120 ]] && INPUT_SIZE_CATEGORY=1
+	      [[ $NEW_WIDTH -ge 120 ]] && INPUT_SIZE_CATEGORY=2
+	      [[ $NEW_WIDTH -ge 240 ]] && INPUT_SIZE_CATEGORY=3
+	      [[ $NEW_WIDTH -ge 320 ]] && INPUT_SIZE_CATEGORY=4
+	      [[ $NEW_WIDTH -ge 480 ]] && INPUT_SIZE_CATEGORY=5
+	      [[ $NEW_WIDTH -ge 640 ]] && INPUT_SIZE_CATEGORY=6
+	      [[ $NEW_WIDTH -ge 848 ]] && INPUT_SIZE_CATEGORY=7
+	      [[ $NEW_WIDTH -ge 1280 ]] && INPUT_SIZE_CATEGORY=8
+
+	      [[ $DEBUG -gt 0 ]] && echo  "INPUT_SIZE_CATEGORY=$INPUT_SIZE_CATEGORY"
+	      save_info "INPUT_SIZE_CATEGORY=$INPUT_SIZE_CATEGORY"
+
+# 	      # check the BPF of the video (test)
+# 	      NB_FRAMES=$(mediainfo "--Inform=Video;%FrameCount%" ${INPUT})
+# 	      STREAMSIZE=$(mediainfo "--Inform=Video;%StreamSize%" ${INPUT})
+# 	      NB_PIXELS=$(echo "$WIDTH * $HEIGHT"|bc)
+# 	      if [[ ! -z $STREAMSIZE && ! -z $NB_FRAMES ]]
+# 	      then
+# 	      NB_PIXELS=$(echo "$WIDTH * $HEIGHT"|bc)
+# 	      BPF=$(echo "($STREAMSIZE * 1080 / $NB_FRAMES) / $NB_PIXELS  "|bc)
+# 	      echo -e "fredo BPF1=${GREEN}${BPF}${NC}"
+# 	      fi
+	    
+
+
+  
+# 	      # check the BPF of the video
+# 	      
+# 	      BPF=$(mediainfo "--Inform=Video;%Bits-(Pixel*Frame)%" ${INPUT})
+# 	           
+# 	      if [[ $BPF < $MINIMUM_BPF && ! -z $BPF ]] 
+# 	      then
+# 	      WARNING="WARNING: BPF quality  of the video is ($BPF).The minimun quality is ($MINIMUM_BPF)  "
+# 	      echo -e "${PINK}$WARNING${NC}"
+# 	      echo $WARNING >> ${DIRECTORY}/${OUTPUT}/warning.txt
+# 	      else
+# 	      echo  -e "BPF=${GREEN}${BPF}${NC}"
+# 	      fi
+	      
+
+
+	      
+# 	      VBRPP=$(echo "scale=1;$BITERATE / $NB_PIXELS  "|bc)
+# 	      if [[ $VBRPP <  1.5  ]]
+# 	      then
+# 	      WARNING="WARNING: VBRPP quality  of the video is ($VBRPP).The minimun quality is (1)  "
+# 	      echo -e "${PINK}$WARNING${NC}"
+# 	      echo $WARNING >> ${DIRECTORY}/${OUTPUT}/warning.txt
+# 	      else
+# 	      echo -e "fredo VBRPP=${GREEN}${VBRPP}${NC}"
+# 	      fi
+
+
+
+
 }
 
